# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('physical_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=7)),
                ('birthdate', models.DateField()),
                ('deathdate', models.DateField(blank=True)),
                ('genotype_confirmation', models.CharField(blank=True, max_length=30, null=True)),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('pfa_liver', models.BooleanField(default=False)),
                ('pfa_liver_tumor', models.BooleanField(default=False)),
                ('pfa_small_intenstine', models.BooleanField(default=False)),
                ('pfa_small_intenstine_tumor', models.BooleanField(default=False)),
                ('pfa_skin', models.BooleanField(default=False)),
                ('pfa_skin_hair', models.BooleanField(default=False)),
                ('pfa_other', models.CharField(blank=True, max_length=20, null=True)),
                ('freezedown_liver', models.BooleanField(default=False)),
                ('freezedown_liver_tumor', models.BooleanField(default=False)),
                ('freezedown_other', models.CharField(blank=True, max_length=20, null=True)),
                ('genotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mousemanagement.Genotype')),
            ],
        ),
        migrations.CreateModel(
            name='Mouseline',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project_title',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sacrificer',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='mouse',
            name='mouseline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mousemanagement.Mouseline'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='phenotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mousemanagement.Phenotype'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='project_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mousemanagement.Project_title'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='sacrificer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mousemanagement.Sacrificer'),
        ),
    ]
